on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Make
      run:  make

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: 'Flash Loader'
        path: dp32-fl.elf

    - name: 'Create Release'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dp32-fl.elf,Devices.xml"

